# Learn_Python_Ka_Chilla_With_Baba_Ammar
---


### Tittle "Research Scholar"
### Name "Muhammad Hasnain"
### Email "mhasnain@ele.qau.edu.pk"
### What'sp no "+92-3006712492"
### Telegram no "+92-3006054928"
----

### Numpy
---

In [1]:
Hasnain = [1,2,3,4,5,6,7]
Hasnain

[1, 2, 3, 4, 5, 6, 7]

In [6]:
Hasnain = (" There is a hasnain")
Hasnain
type(Hasnain)

str

In [3]:
Hasnain = ['Apple','banana','Orange','Patato']
Hasnain

['Apple', 'banana', 'Orange', 'Patato']

In [5]:
type(Hasnain)

list

In [7]:
Hasnain = {'Orange':50,'Apple':90,'Orange':100}
Hasnain

{'Orange': 100, 'Apple': 90}

In [8]:
type(Hasnain)

dict

In [10]:
Data = ([[10.5,15.28,45,98,100],[25,25.8,90.9,19]])
Data

[[10.5, 15.28, 45, 98, 100], [25, 25.8, 90.9, 19]]

In [11]:
Data*2

[[10.5, 15.28, 45, 98, 100],
 [25, 25.8, 90.9, 19],
 [10.5, 15.28, 45, 98, 100],
 [25, 25.8, 90.9, 19]]

In [25]:
Data+Data

[[10.5, 15.28, 45, 98, 100],
 [25, 25.8, 90.9, 19],
 [10.5, 15.28, 45, 98, 100],
 [25, 25.8, 90.9, 19]]

In [29]:
import numpy as np 
nuro1 = [6,7.5,8,0,0.1]
arr1 = np.array(nuro1)

In [30]:
arr1

array([6. , 7.5, 8. , 0. , 0.1])

In [36]:
nuro2 = [[1,2,3,4,5], [6,7,8,9,10]]
arr2 = np.array(nuro2)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [37]:
arr2.ndim

2

In [38]:
arr2.shape

(2, 5)

In [39]:
arr1.dtype

dtype('float64')

In [40]:
arr2.shape

(2, 5)

In [41]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [42]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [44]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [45]:
np.empty((2,3,6))

array([[[4.00540117e-307, 1.10345756e-312, 2.22519099e-307,
         2.33647355e-307, 6.23040373e-307, 1.60219035e-306],
        [1.69121503e-306, 3.44902066e-307, 1.60214553e-306,
         2.14325396e-312, 2.22519099e-307, 2.33647355e-307],
        [4.22790516e-307, 4.00536722e-307, 6.23040373e-307,
         1.60219035e-306, 1.69121503e-306, 3.44902066e-307]],

       [[1.60214553e-306, 2.14325396e-312, 5.11787699e-307,
         1.37961370e-306, 3.33777206e-307, 1.89144859e-307],
        [1.61324815e-307, 2.46154653e-312, 2.67023123e-307,
         6.23040373e-307, 1.60219035e-306, 1.69121503e-306],
        [7.56587585e-307, 1.37961302e-306, 1.05699242e-307,
         6.23040373e-307, 1.60219035e-306, 1.69121503e-306]]])

In [47]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [50]:
arr1.dtype

dtype('int32')

In [51]:
arr = np.array([10,20,30,60,58])

In [52]:
arr

array([10, 20, 30, 60, 58])

In [54]:
arr.dtype

dtype('int32')

In [60]:
float_arr = arr.astype(np.float64)    

In [59]:
float_arr.dtype

dtype('float64')

In [62]:
arr.astype(np.int32)

array([10, 20, 30, 60, 58])

In [66]:
numric_strings = np.array(['1.25','-9.6',42],dtype=np.string_)
numric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [67]:
int_array = np.arange(10)

In [69]:
calibers = np.array([.22,.270,.80], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [72]:
arr = np.array([[1.,2.,3.,3.],[4.,5.,6.,7.]])
arr

array([[1., 2., 3., 3.],
       [4., 5., 6., 7.]])

In [73]:
arr*arr

array([[ 1.,  4.,  9.,  9.],
       [16., 25., 36., 49.]])

In [74]:
arr-arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
1/arr

array([[1.        , 0.5       , 0.33333333, 0.33333333],
       [0.25      , 0.2       , 0.16666667, 0.14285714]])

In [77]:
arr**3

array([[  1.,   8.,  27.,  27.],
       [ 64., 125., 216., 343.]])

In [78]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
arr[4:7]

array([4, 5, 6])

In [82]:
arr[5:8] = 12

In [83]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [84]:
arr_slice = arr[5:8]

In [87]:
arr_slice[1] =64

In [88]:
arr

array([ 0,  1,  2,  3,  4, 12, 64, 64,  8,  9])

In [89]:
arr_slice[:]= 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [90]:
arr[5:8].copy()

array([64, 64, 64])

In [91]:
#Arr2d# Two dimesion Array

In [92]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
arr2d[2]

array([7, 8, 9])

In [95]:
arr2d[0]

array([1, 2, 3])

In [97]:
arr2d[1]

array([4, 5, 6])

In [98]:
arr2d[0,2]

3

In [102]:
arr2d[0,1]

2

In [103]:
arr3d = np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [106]:
arr3d[0]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [110]:
arr3d[0] = 42

In [108]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42],
        [42, 42, 42],
        [42, 42, 42]]])

In [112]:
arr3d[0,1]

array([42, 42, 42])

In [115]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [116]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [117]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [119]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [122]:
 names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [125]:
arr = np.empty((8, 4))


In [126]:
arr

array([[1.21106744e-311, 1.03753786e-321, 0.00000000e+000,
        0.00000000e+000],
       [2.41907520e-312, 5.02034658e+175, 1.91924948e-076,
        1.61637724e+160],
       [3.12377100e-033, 6.95773370e-042, 8.29846127e-067,
        2.16385130e+190],
       [1.94918964e-153, 5.30581644e+180, 1.04678090e-142,
        1.06396443e+224],
       [1.70100503e+256, 5.49109388e-143, 9.30537467e+199,
        3.10716137e-033],
       [2.36842528e+179, 5.93303216e-038, 3.30664223e+179,
        4.91851280e-143],
       [5.49810101e-143, 5.27606290e-091, 1.41019845e-076,
        3.67345353e-062],
       [4.29599742e-096, 4.82337433e+228, 3.67152456e-062,
        1.20954166e-311]])

In [128]:
for i in range(8):arr[i] = i


In [129]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [130]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [131]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [132]:
arr = np.arange(32).reshape((8, 4))


In [133]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [134]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [135]:
 arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [136]:
arr[np.ix_([1, 5, 7, 2], [0, 3, 1, 2])]


array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [137]:
arr = np.arange(15).reshape((3, 5))


In [138]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [142]:
arr = np.arange(30).reshape((6,5))

In [143]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [144]:
arr.T

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [145]:
arr = np.random.randn(6, 3)


In [146]:
arr

array([[ 1.54637097,  1.75745085,  1.03469379],
       [ 1.11608907,  1.27540248, -1.22802967],
       [-0.66333317,  0.55500834,  0.07718483],
       [-2.02078644, -0.34045265, -1.17090688],
       [ 2.64703589, -0.03370059,  1.12909969],
       [ 0.77718947, -1.21452263, -0.05809379]])

In [147]:
np.dot(arr.T, arr)

array([[15.77132918,  3.42783953,  5.48800095],
       [ 3.42783953,  6.61542821,  0.72617288],
       [ 5.48800095,  0.72617288,  5.23386953]])

In [148]:
np.dot(arr.T,arr)

array([[15.77132918,  3.42783953,  5.48800095],
       [ 3.42783953,  6.61542821,  0.72617288],
       [ 5.48800095,  0.72617288,  5.23386953]])

In [149]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [150]:
arr.transpose((1, 0, 2))


array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [151]:
arr = np.arange(10)
np.sqrt(arr)



array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])